const copy = {
  brand: { name: "Novalup AI", product: "Product Photos" },
  landing: {
    headline: "Convertí las fotos de tu producto en imágenes de marketing profesionales con IA.",
    subheadline: "Subí tu producto, elegí un estilo y generá una imagen profesional en segundos.",
    ctaFree: (n: number) => `Probá y generá ${n} ${n === 1 ? "imagen" : "imágenes"} gratis`,
    login: "Iniciar sesión",
    signup: "Crear cuenta",
    demoBefore: "Antes",
    demoAfter: "Después",
  },
  auth: {
    loginTitle: "Iniciá sesión",
    signupTitle: "Creá tu cuenta",
    name: "Nombre",
    email: "Email",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    submitLogin: "Iniciar sesión",
    submitSignup: "Crear cuenta",
    google: "Continuar con Google",
    haveAccount: "¿Ya tenés cuenta?",
    noAccount: "¿No tenés cuenta?",
    or: "o",
    signOut: "Cerrar sesión",
  },
  tool: {
    title: "Creá una foto de producto",
    subtitle: "Subí tu producto y dejá que la IA cree una imagen de marketing profesional.",
    uploadHint: "Arrastrá una imagen o hacé clic para subirla",
    uploadFormats: "JPG, PNG o WEBP · hasta 10 MB",
    removeImage: "Quitar imagen",
    photoCountLabel: "Cantidad de imágenes",
    photoCountHint: "1 crédito por imagen",
    photoNLabel: (i: number) => `Foto ${i}`,
    photoTabsLabel: "Fotos a generar",
    photoTabIncomplete: "Faltan opciones por elegir",
    referencesHint: "hasta 2 imágenes de referencia",
    formatLabel: "Formato",
    styleLabel: "Estilo",
    backgroundLabel: "Fondo",
    instructionsLabel: "Instrucciones adicionales",
    instructionsPlaceholder: "¿Algo más que quieras que la IA tenga en cuenta?",
    optionsPlaceholder: "Subí una imagen para elegir formato, estilo y fondo.",
    formats: { "1:1": "Cuadrado 1:1", "4:5": "Retrato 4:5", "9:16": "Vertical 9:16", "16:9": "Horizontal 16:9" },
    formatHints: {
      "1:1": "Cuadrado. Ideal para el feed de Instagram, catálogos y miniaturas.",
      "4:5": "Retrato. Ocupa más pantalla en el feed de Instagram y Facebook.",
      "9:16": "Vertical completo. Para historias y Reels / TikTok.",
      "16:9": "Horizontal. Para web, banners y presentaciones.",
    },
    styles: { studio: "Estudio", lifestyle: "Estilo de vida", luxury: "Lujo", minimal: "Minimalista", "social-media": "Redes sociales" },
    styleHints: {
      studio: "Fondo de estudio uniforme y luz pareja controlada. El clásico para e-commerce y catálogo.",
      lifestyle: "El producto usado en un entorno real, con luz natural suave. Transmite cómo se ve en la vida cotidiana.",
      luxury: "Estética editorial premium: composición elegante, luz dramática y dirigida, aire de revista.",
      minimal: "Composición moderna y despejada, mucho espacio vacío y una paleta sobria.",
      "social-media": "Encuadre llamativo y de alto contraste, pensado para frenar el scroll en redes.",
    },
    backgrounds: { clean: "Limpio", premium: "Premium", natural: "Natural", custom: "Personalizado" },
    backgroundHints: {
      clean: "Superficie neutra y sin distracciones: toda la atención va al producto.",
      premium: "Entorno con texturas sutiles como piedra, metal cepillado o tela fina.",
      natural: "Entorno natural con materiales orgánicos: plantas, madera o luz de día.",
      custom: "Vos describís el fondo en el campo de instrucciones adicionales de abajo.",
    },
    generateN: (n: number) => n === 1 ? "✨ Generar imagen" : `✨ Generar ${n} imágenes · ${n} créditos`,
    generating: "Creando tu foto de producto…",
    generatingTitle: (n: number) => n === 1 ? "Generando tu imagen…" : `Generando tus ${n} imágenes…`,
    generatingSubtitle: (n: number) => n === 1
      ? "Estamos preparando una foto profesional de tu producto."
      : `Estamos preparando ${n} fotos profesionales de tu producto.`,
    generatingSteps: ["Analizando producto", "Aplicando estilo", "Creando escenario", "Generando imagen"],
    creatingBatch: (done: number, total: number) =>
      total === 1
        ? `Creando tu foto… ${done} de 1 lista`
        : `Creando ${total} fotos… ${done} de ${total} listas`,
    userMenuLabel: "Menú de usuario",
    myCreations: "Mis creaciones",
    resultTitle: "Tu foto de producto",
    resultsTitle: (n: number) =>
      n === 0 ? "No pudimos generar tus imágenes"
        : n === 1 ? "✨ Tu imagen está lista"
        : `✨ Tus ${n} imágenes están listas`,
    resultsSubtitle: (n: number) =>
      n === 1 ? "Generada a partir de tu producto" : "Generadas a partir de tu producto",
    download: "Descargar",
    downloadImage: "↓ Descargar imagen",
    downloadOne: "↓ Descargar",
    createAnother: "Crear otra",
    creditsNeeded: (needed: number, available: number) => `Necesitás ${needed} ${needed === 1 ? "crédito" : "créditos"} · tenés ${available}`,
    batchSummary: (done: number, remaining: number) => `${done} ${done === 1 ? "foto" : "fotos"} · ${done} ${done === 1 ? "crédito usado" : "créditos usados"} · te quedan ${remaining}`,
    creationsTitle: "Mis creaciones",
    noCreations: "Todavía no tenés generaciones.",
    dateLabel: (date: Date | string) => new Date(date).toLocaleDateString("es-AR", { year: "numeric", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }),
    imageLabel: "Imagen generada",
    referenceLabel: "Referencia",
    creationsInstructionsLabel: "Indicaciones",
    promptLabel: "Prompt",
    statusCompleted: "Completada",
    statusFailed: "Fallida",
    statusPending: "Pendiente",
  },
  credits: {
    freeLabel: (n: number) => `${n} créditos gratis`,
    remainingLabel: (n: number) => `${n} créditos restantes`,
  },
  outOfCredits: {
    title: "Te quedaste sin créditos",
    body: "Usaste todas tus generaciones gratuitas. Pronto vas a poder cargar más generaciones para seguir creando. Mientras tanto, contanos qué te pareció la app.",
  },
  feedback: {
    popupTitle: "¿Qué te pareció?",
    openButton: "Dejar feedback",
    title: "Contanos qué te pareció",
    messageLabel: "Tu comentario sobre la app",
    messagePlaceholder: "¿Qué te gustó? ¿Qué mejorarías? ¿Qué te gustaría poder generar?",
    submit: "Enviar feedback",
    sending: "Enviando…",
    close: "Cerrar",
    thanksTitle: "¡Gracias por tu feedback!",
    thanksBody: "Lo vamos a tener en cuenta para mejorar la app.",
  },
  errors: {
    generic: "Algo salió mal. Probá de nuevo.",
    generationFailed: "No pudimos generar la imagen. No se descontó ningún crédito.",
    invalidImage: "El archivo debe ser JPG, PNG o WEBP y pesar menos de 10 MB.",
    inProgress: "Ya tenés una generación en curso.",
    tooManyImages: (max: number) => `Podés subir hasta ${max} imágenes de referencia.`,
    passwordMismatch: "Las contraseñas no coinciden.",
    emailTaken: "Ya existe una cuenta con ese email.",
    invalidCredentials: "Email o contraseña incorrectos.",
  },
} as const;

export default copy;
