const copy = {
  brand: { name: "Novalup AI", product: "Product Photos" },
  landing: {
    headline: "Convertí las fotos de tu producto en imágenes de marketing profesionales con IA.",
    subheadline: "Subí una foto, elegí un estilo y obtené una imagen lista para vender en segundos.",
    cta: "Creá tu primera foto de producto",
    login: "Iniciar sesión",
    signup: "Crear cuenta",
    demoBefore: "Antes",
    demoAfter: "Después",
  },
  auth: {
    loginTitle: "Iniciá sesión",
    signupTitle: "Creá tu cuenta",
    name: "Nombre",
    email: "Email",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    submitLogin: "Iniciar sesión",
    submitSignup: "Crear cuenta",
    google: "Continuar con Google",
    haveAccount: "¿Ya tenés cuenta?",
    noAccount: "¿No tenés cuenta?",
    or: "o",
    signOut: "Cerrar sesión",
  },
  tool: {
    title: "Creá una foto de producto",
    subtitle: "Subí tu producto y dejá que la IA cree una imagen de marketing profesional.",
    uploadHint: "Arrastrá una imagen o hacé clic para subirla",
    uploadFormats: "JPG, PNG o WEBP · hasta 10 MB",
    changeImage: "Cambiar imagen",
    removeImage: "Quitar imagen",
    photoCountLabel: "Cantidad de fotos",
    photoCountOption: (n: number) => n === 1 ? "1 foto" : `${n} fotos`,
    photoNLabel: (i: number) => `Foto ${i}`,
    referencesHint: "hasta 2 imágenes de referencia",
    addReference: "Agregá otra referencia",
    formatLabel: "Formato",
    styleLabel: "Estilo",
    backgroundLabel: "Fondo",
    instructionsLabel: "Instrucciones adicionales",
    instructionsPlaceholder: "¿Algo más que quieras que la IA tenga en cuenta?",
    formats: { "1:1": "Cuadrado 1:1", "4:5": "Retrato 4:5", "9:16": "Vertical 9:16", "16:9": "Horizontal 16:9" },
    styles: { studio: "Studio", lifestyle: "Lifestyle", luxury: "Luxury", minimal: "Minimal", "social-media": "Social Media" },
    backgrounds: { clean: "Clean", premium: "Premium", natural: "Natural", custom: "Custom" },
    generate: "Generar foto",
    generateN: (n: number) => n === 1 ? "Generar foto" : `Generar ${n} fotos`,
    generating: "Creando tu foto de producto…",
    creatingBatch: (done: number, total: number) => `Creando ${total} fotos… ${done} de ${total} listas`,
    userMenuLabel: "Menú de usuario",
    resultTitle: "Tu foto de producto",
    generateAgain: "Generar de nuevo",
    download: "Descargar",
    createAnother: "Crear otra",
    creditUsed: (remaining: number) => `1 crédito usado · Te quedan ${remaining} créditos`,
    creditsNeeded: (needed: number, available: number) => `Necesitás ${needed} ${needed === 1 ? "crédito" : "créditos"} · tenés ${available}`,
    batchSummary: (done: number, remaining: number) => `${done} ${done === 1 ? "foto" : "fotos"} · ${done} ${done === 1 ? "crédito usado" : "créditos usados"} · te quedan ${remaining}`,
  },
  credits: {
    freeLabel: (n: number) => `${n} créditos gratis`,
    remainingLabel: (n: number) => `${n} créditos restantes`,
  },
  outOfCredits: {
    title: "Te quedaste sin créditos gratis",
    body: "Usaste todas tus generaciones gratuitas. Estamos trabajando en una forma de que sigas creando más fotos de producto.",
  },
  feedback: {
    title: "Contanos qué te pareció",
    name: "Nombre",
    email: "Email",
    thoughts: "¿Qué te pareció la herramienta?",
    nextIdeas: "¿Qué te gustaría generar después?",
    submit: "Enviar feedback",
    sending: "Enviando…",
    thanksTitle: "¡Gracias por tu feedback!",
    thanksBody: "Te avisamos cuando haya más créditos disponibles.",
  },
  errors: {
    generic: "Algo salió mal. Probá de nuevo.",
    generationFailed: "No pudimos generar la imagen. No se descontó ningún crédito.",
    invalidImage: "El archivo debe ser JPG, PNG o WEBP y pesar menos de 10 MB.",
    inProgress: "Ya tenés una generación en curso.",
    tooManyImages: (max: number) => `Podés subir hasta ${max} imágenes de referencia.`,
    passwordMismatch: "Las contraseñas no coinciden.",
    emailTaken: "Ya existe una cuenta con ese email.",
    invalidCredentials: "Email o contraseña incorrectos.",
  },
} as const;

export default copy;
